name: Code style
on:
  push:
    branches:
      - stable
      - testing
      - dev
  pull_request:
    branches:
      - stable
      - testing
      - dev
permissions:
  contents: read
jobs:
  main:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
    env:
      NODE_ENV: cicd
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Install Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Check code format
        run: npm run format:check
      - name: Check code style
        run: npm run lint:check
      - name: Check type definitions
        run: npm run type:check
